#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2021, Cisco Systems
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

DOCUMENTATION = r"""
---
module: sda_virtual_network_ip_pool
short_description: Resource module for Sda Virtual Network Ip Pool
description:
- Manage operations create and delete of the resource Sda Virtual Network Ip Pool.
- Add IP Pool in SDA Virtual Network.
- Delete IP Pool from SDA Virtual Network.
version_added: '3.1.0'
extends_documentation_fragment:
  - cisco.dnac.module
author: Rafael Campos (@racampos)
options:
  autoGenerateVlanName:
    version_added: "6.0.0"
    description: It will auto generate vlanName, if vlanName is empty(applicable for
      L3 and INFRA_VN).
    type: bool
  ipPoolName:
    version_added: "4.0.0"
    description: IpPoolName query parameter.
    type: str
  isCommonPool:
    version_added: "6.0.0"
    description: Common Pool enablement flag(applicable for L3 and L2).
    type: bool
  isIpDirectedBroadcast:
    version_added: "6.0.0"
    description: Ip Directed Broadcast enablement flag(applicable for L3).
    type: bool
  isL2FloodingEnabled:
    version_added: "4.0.0"
    description: Layer2 flooding enablement flag(applicable for L3 , L2 and always true
      for L2).
    type: bool
  isLayer2Only:
    version_added: "6.0.0"
    description: Layer2 Only enablement flag.
    type: str
  isThisCriticalPool:
    version_added: "4.0.0"
    description: Critical pool enablement(applicable for L3).
    type: bool
  isWirelessPool:
    version_added: "4.0.0"
    description: Wireless Pool enablement flag(applicable for L3 and L2).
    type: bool
  poolType:
    version_added: "4.0.0"
    description: Pool Type (applicable for INFRA_VN).
    type: str
  scalableGroupName:
    version_added: "4.0.0"
    description: Scalable Group Name(applicable for L3).
    type: str
  siteNameHierarchy:
    version_added: "4.0.0"
    description: SiteNameHierarchy query parameter.
    type: str
  trafficType:
    version_added: "4.0.0"
    description: Traffic type(applicable for L3 and L2).
    type: str
  virtualNetworkName:
    description: VirtualNetworkName query parameter.
    type: str
  vlanId:
    version_added: "6.0.0"
    description: Vlan Id(applicable for L3 , L2 and INFRA_VN).
    type: str
  vlanName:
    version_added: "4.0.0"
    description: Vlan name represent the segment name, if empty, vlanName would be auto
      generated by API.
    type: str
requirements:
- dnacentersdk == 2.4.5
- python >= 3.5
notes:
  - SDK Method used are
    sda.Sda.add_ip_pool_in_sda_virtual_network,
    sda.Sda.delete_ip_pool_from_sda_virtual_network,

  - Paths used are
    post /dna/intent/api/v1/business/sda/virtualnetwork/ippool,
    delete /dna/intent/api/v1/business/sda/virtualnetwork/ippool,

"""

EXAMPLES = r"""
- name: Delete all
  cisco.dnac.sda_virtual_network_ip_pool:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    state: absent
    ipPoolName: string
    siteNameHierarchy: string
    virtualNetworkName: string

- name: Create
  cisco.dnac.sda_virtual_network_ip_pool:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    state: present
    autoGenerateVlanName: true
    ipPoolName: string
    isCommonPool: true
    isIpDirectedBroadcast: true
    isL2FloodingEnabled: true
    isLayer2Only: string
    isThisCriticalPool: true
    isWirelessPool: true
    poolType: string
    scalableGroupName: string
    siteNameHierarchy: string
    trafficType: string
    virtualNetworkName: string
    vlanId: string
    vlanName: string

"""

RETURN = r"""
dnac_response:
  description: A dictionary or list with the response returned by the Cisco DNAC Python SDK
  returned: always
  type: dict
  sample: >
    {
      "status": "string",
      "description": "string",
      "taskId": "string",
      "taskStatusUrl": "string",
      "executionStatusUrl": "string",
      "executionId": "string"
    }
"""
